server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: clientes
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Clientes
    username: postgres
    password: SoloMillos
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8081
  cloud:
    feign:
      # Activa la configuración de Feign
      config:
        default:
          # Decodifica la respuesta a JSON
          decoder: feign.codec.JacksonDecoder
          # Codifica la solicitud a JSON
          encoder: feign.codec.JacksonEncoder
          # Establece el tiempo de espera de conexión
          connectTimeout: 5000
          # Establece el tiempo de espera de lectura
          readTimeout: 5000
